# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/JVO/Documents/Jogo_Tecprog

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/JVO/Documents/Jogo_Tecprog

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/JVO/Documents/Jogo_Tecprog/CMakeFiles /home/JVO/Documents/Jogo_Tecprog//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/JVO/Documents/Jogo_Tecprog/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Jogo_Tecprog

# Build rule for target.
Jogo_Tecprog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Jogo_Tecprog
.PHONY : Jogo_Tecprog

# fast build rule for target.
Jogo_Tecprog/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/build
.PHONY : Jogo_Tecprog/fast

#=============================================================================
# Target rules for targets named testes

# Build rule for target.
testes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testes
.PHONY : testes

# fast build rule for target.
testes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/build
.PHONY : testes/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/main.cpp.s
.PHONY : main.cpp.s

src/Ente.o: src/Ente.cpp.o
.PHONY : src/Ente.o

# target to build an object file
src/Ente.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/src/Ente.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/src/Ente.cpp.o
.PHONY : src/Ente.cpp.o

src/Ente.i: src/Ente.cpp.i
.PHONY : src/Ente.i

# target to preprocess a source file
src/Ente.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/src/Ente.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/src/Ente.cpp.i
.PHONY : src/Ente.cpp.i

src/Ente.s: src/Ente.cpp.s
.PHONY : src/Ente.s

# target to generate assembly for a file
src/Ente.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/src/Ente.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/src/Ente.cpp.s
.PHONY : src/Ente.cpp.s

src/Jogo.o: src/Jogo.cpp.o
.PHONY : src/Jogo.o

# target to build an object file
src/Jogo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/src/Jogo.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/src/Jogo.cpp.o
.PHONY : src/Jogo.cpp.o

src/Jogo.i: src/Jogo.cpp.i
.PHONY : src/Jogo.i

# target to preprocess a source file
src/Jogo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/src/Jogo.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/src/Jogo.cpp.i
.PHONY : src/Jogo.cpp.i

src/Jogo.s: src/Jogo.cpp.s
.PHONY : src/Jogo.s

# target to generate assembly for a file
src/Jogo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/src/Jogo.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/src/Jogo.cpp.s
.PHONY : src/Jogo.cpp.s

src/gerenciadores/GerenciadorGrafico.o: src/gerenciadores/GerenciadorGrafico.cpp.o
.PHONY : src/gerenciadores/GerenciadorGrafico.o

# target to build an object file
src/gerenciadores/GerenciadorGrafico.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/src/gerenciadores/GerenciadorGrafico.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/src/gerenciadores/GerenciadorGrafico.cpp.o
.PHONY : src/gerenciadores/GerenciadorGrafico.cpp.o

src/gerenciadores/GerenciadorGrafico.i: src/gerenciadores/GerenciadorGrafico.cpp.i
.PHONY : src/gerenciadores/GerenciadorGrafico.i

# target to preprocess a source file
src/gerenciadores/GerenciadorGrafico.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/src/gerenciadores/GerenciadorGrafico.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/src/gerenciadores/GerenciadorGrafico.cpp.i
.PHONY : src/gerenciadores/GerenciadorGrafico.cpp.i

src/gerenciadores/GerenciadorGrafico.s: src/gerenciadores/GerenciadorGrafico.cpp.s
.PHONY : src/gerenciadores/GerenciadorGrafico.s

# target to generate assembly for a file
src/gerenciadores/GerenciadorGrafico.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Jogo_Tecprog.dir/build.make CMakeFiles/Jogo_Tecprog.dir/src/gerenciadores/GerenciadorGrafico.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/src/gerenciadores/GerenciadorGrafico.cpp.s
.PHONY : src/gerenciadores/GerenciadorGrafico.cpp.s

testes/ente/teste_Ente.o: testes/ente/teste_Ente.cpp.o
.PHONY : testes/ente/teste_Ente.o

# target to build an object file
testes/ente/teste_Ente.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/testes/ente/teste_Ente.cpp.o
.PHONY : testes/ente/teste_Ente.cpp.o

testes/ente/teste_Ente.i: testes/ente/teste_Ente.cpp.i
.PHONY : testes/ente/teste_Ente.i

# target to preprocess a source file
testes/ente/teste_Ente.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/testes/ente/teste_Ente.cpp.i
.PHONY : testes/ente/teste_Ente.cpp.i

testes/ente/teste_Ente.s: testes/ente/teste_Ente.cpp.s
.PHONY : testes/ente/teste_Ente.s

# target to generate assembly for a file
testes/ente/teste_Ente.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/testes/ente/teste_Ente.cpp.s
.PHONY : testes/ente/teste_Ente.cpp.s

testes/gerenciadores/teste_GerenciadorGrafico.o: testes/gerenciadores/teste_GerenciadorGrafico.cpp.o
.PHONY : testes/gerenciadores/teste_GerenciadorGrafico.o

# target to build an object file
testes/gerenciadores/teste_GerenciadorGrafico.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/testes/gerenciadores/teste_GerenciadorGrafico.cpp.o
.PHONY : testes/gerenciadores/teste_GerenciadorGrafico.cpp.o

testes/gerenciadores/teste_GerenciadorGrafico.i: testes/gerenciadores/teste_GerenciadorGrafico.cpp.i
.PHONY : testes/gerenciadores/teste_GerenciadorGrafico.i

# target to preprocess a source file
testes/gerenciadores/teste_GerenciadorGrafico.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/testes/gerenciadores/teste_GerenciadorGrafico.cpp.i
.PHONY : testes/gerenciadores/teste_GerenciadorGrafico.cpp.i

testes/gerenciadores/teste_GerenciadorGrafico.s: testes/gerenciadores/teste_GerenciadorGrafico.cpp.s
.PHONY : testes/gerenciadores/teste_GerenciadorGrafico.s

# target to generate assembly for a file
testes/gerenciadores/teste_GerenciadorGrafico.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/testes/gerenciadores/teste_GerenciadorGrafico.cpp.s
.PHONY : testes/gerenciadores/teste_GerenciadorGrafico.cpp.s

testes/teste_main.o: testes/teste_main.cpp.o
.PHONY : testes/teste_main.o

# target to build an object file
testes/teste_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/testes/teste_main.cpp.o
.PHONY : testes/teste_main.cpp.o

testes/teste_main.i: testes/teste_main.cpp.i
.PHONY : testes/teste_main.i

# target to preprocess a source file
testes/teste_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/testes/teste_main.cpp.i
.PHONY : testes/teste_main.cpp.i

testes/teste_main.s: testes/teste_main.cpp.s
.PHONY : testes/teste_main.s

# target to generate assembly for a file
testes/teste_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testes.dir/build.make CMakeFiles/testes.dir/testes/teste_main.cpp.s
.PHONY : testes/teste_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Jogo_Tecprog"
	@echo "... testes"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Ente.o"
	@echo "... src/Ente.i"
	@echo "... src/Ente.s"
	@echo "... src/Jogo.o"
	@echo "... src/Jogo.i"
	@echo "... src/Jogo.s"
	@echo "... src/gerenciadores/GerenciadorGrafico.o"
	@echo "... src/gerenciadores/GerenciadorGrafico.i"
	@echo "... src/gerenciadores/GerenciadorGrafico.s"
	@echo "... testes/ente/teste_Ente.o"
	@echo "... testes/ente/teste_Ente.i"
	@echo "... testes/ente/teste_Ente.s"
	@echo "... testes/gerenciadores/teste_GerenciadorGrafico.o"
	@echo "... testes/gerenciadores/teste_GerenciadorGrafico.i"
	@echo "... testes/gerenciadores/teste_GerenciadorGrafico.s"
	@echo "... testes/teste_main.o"
	@echo "... testes/teste_main.i"
	@echo "... testes/teste_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

